
################
### GESTURES ###
################

# Hyprland 0.55+ uses a new gesture system.
# Using 'scale' to make the swipe more fluent/snappy.

gesture = 3, horizontal, workspace, scale=4.0, distance=150
gesture = 4, up, fullscreen
gesture = 4, down, fullscreen