##############################
### WINDOWS AND WORKSPACES ###
##############################

## Use hyprctl clients to look for window class

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

windowrule = float on, match:class jome

# Opacity rules
windowrule = opacity 0.90 0.90, match:class Thorium-browser
windowrule = opacity 0.80 0.80, match:class Code
windowrule = opacity 0.80 0.80, match:class Arduino IDE
windowrule = opacity 0.80 0.80, match:class dev.warp.Warp
windowrule = opacity 0.80 0.80, match:class obsidian
windowrule = opacity 0.80 0.80, match:class code-url-handler
windowrule = opacity 0.80 0.80, match:class code-insiders-url-handler
windowrule = opacity 0.80 0.80, match:class kitty
windowrule = opacity 0.80 0.80, match:class org.gnome.Nautilus
windowrule = opacity 0.80 0.80, match:class org.kde.ark
windowrule = opacity 0.80 0.80, match:class nwg-look
windowrule = opacity 0.80 0.80, match:class qt5ct
windowrule = opacity 0.80 0.80, match:class qt6ct
windowrule = opacity 0.80 0.80, match:class kvantummanager
windowrule = opacity 0.80 0.70, match:class pavucontrol
windowrule = opacity 0.80 0.70, match:class blueman-manager
windowrule = opacity 0.80 0.70, match:class nm-applet
windowrule = opacity 0.70 0.70, match:class Spotify
windowrule = opacity 0.80 0.70, match:class nm-connection-editor
windowrule = opacity 0.80 0.70, match:class org.kde.polkit-kde-authentication-agent-1
windowrule = opacity 0.80 0.70, match:class polkit-gnome-authentication-agent-1
windowrule = opacity 0.80 0.70, match:class org.freedesktop.impl.portal.desktop.gtk
windowrule = opacity 0.80 0.70, match:class org.freedesktop.impl.portal.desktop.hyprland

# Float rules
windowrule = float on, match:class kvantummanager
windowrule = float on, match:class qt5ct
windowrule = float on, match:class qt6ct
windowrule = float on, match:class nwg-look
windowrule = float on, match:class org.kde.ark
windowrule = float on, match:class pavucontrol
windowrule = float on, match:class blueman-manager
windowrule = float on, match:class nm-applet
windowrule = float on, match:class nm-connection-editor
windowrule = float on, match:class org.kde.polkit-kde-authentication-agent-1

# windowrule = suppressevent maximize on, match:class .*

layerrule = blur on, match:namespace waybar
layerrule = ignore_alpha 0.5, match:namespace waybar
layerrule = blur on, match:namespace swaync-control-center
layerrule = ignore_alpha 0.5, match:namespace swaync-control-center
layerrule = animation slide right, match:namespace swaync-control-center
layerrule = animation slide, match:namespace swaync-notification-window
layerrule = blur on, match:namespace tofi
layerrule = ignore_alpha 0, match:namespace tofi
layerrule = blur on, match:namespace dunst
layerrule = ignore_alpha 0, match:namespace dunst
